### ISSUE TITLE
Prod build bug

### ISSUE THREAD

**Issue by ghost** [mgechev/angular2-github-app-bootstrap#1]
line 228 in gulpfile.js should be 

  return gulp.src(['./app/**/*.html', './app/**/_.css', './app/img/_*'].concat(PATH.src.css))

**Comment by mgechev** [comment]
Hi @butterfieldcons, what is the issue do you see in the usage of wildcards?

**Comment by ghost** [comment]
Hi

It's the path that's wrong. Line 228 has bad path. Thanks for hard work.

**Comment by ghost** [comment]
Without phone its easier.You have.....  return gulp.src(['./app/**/*.html', './app/**/_.css', './app/img/__'].concat(PATH.lib.css)) should be.... return gulp.src(['./app/__/_.html', './app/**/*.css', './app/img/**'].concat(PATH.src.css)) On 06/22/15, Minko Gechevnotifications@github.com wrote: Hi @butterfieldcons, what is the issue do you see in the usage of wildcards?—Reply to this email directly or view it on GitHub.

**Comment by mgechev** [comment]
Oh, right! I saw the wrong `PATH.lib.css` reference.

Thanks!
